[client]
toolbarMode = "minimal"
showErrorDetails = true

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#a3e635"
backgroundColor = "#0a0e14"
secondaryBackgroundColor = "#141a23"
textColor = "#f5f5f5"
